{
 "title": "Spacelift Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Billing Period Start",
   "type": "stat",
   "description": "Shows the start of your billing period. This will only display if you have signed up for self-service via Stripe rather than being on an enterprise billing contract.",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(spacelift_current_billing_period_start_timestamp_seconds) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Public Minutes Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(spacelift_current_billing_period_used_public_seconds) / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Private Minutes Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(spacelift_current_billing_period_used_private_seconds) / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Seats",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(spacelift_current_billing_period_used_seats)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Billing Period End",
   "type": "stat",
   "description": "Shows the end of your billing period. This will only display if you have signed up for self-service via Stripe rather than being on an enterprise billing contract.",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(spacelift_current_billing_period_end_timestamp_seconds) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time until usage resets",
   "type": "stat",
   "description": "Shows the amount of time until your usage quota resets.. This will only display if you have signed up for self-service via Stripe rather than being on an enterprise billing contract.",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(max(spacelift_current_billing_period_end_timestamp_seconds) - time(), 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Public Worker Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Parallelism",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(spacelift_public_worker_pool_parallelism)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runs Executing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(spacelift_public_worker_pool_workers_busy)",
     "legendFormat": "Runs"
    }
   ]
  },
  {
   "title": "Busy Workers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(spacelift_public_worker_pool_workers_busy)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Runs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(spacelift_public_worker_pool_runs_pending)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Private Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Busy Workers",
   "type": "timeseries",
   "description": "Shows the number of workers busy by worker pool.",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(spacelift_worker_pool_workers_busy) by (worker_pool_id, worker_pool_name) > 0",
     "legendFormat": "{{worker_pool_name}} ({{worker_pool_id}})"
    }
   ]
  },
  {
   "title": "Pending Runs",
   "type": "timeseries",
   "description": "Shows the number of pending runs by worker pool.",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(spacelift_worker_pool_runs_pending) by (worker_pool_id, worker_pool_name) > 0",
     "legendFormat": "{{worker_pool_name}} ({{worker_pool_id}})"
    }
   ]
  },
  {
   "title": "Private Worker Pools",
   "type": "table",
   "description": "Shows the list of private worker pools in the account, along with information about each pool.",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "max(spacelift_worker_pool_workers) by (worker_pool_id, worker_pool_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(spacelift_worker_pool_workers_busy) by (worker_pool_id, worker_pool_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(spacelift_worker_pool_runs_pending) by (worker_pool_id, worker_pool_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(spacelift_worker_pool_workers_drained) by (worker_pool_id, worker_pool_name)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}