---
- name: Manage Single PanOS Appliance
  gather_facts: yes
  hosts: localhost
  vars:
    # The IP addresses of the untrust interface of the Palo Alto firewall. Always start with a network address first followed by the additional host IPs, IE: ["10.0.2.101/24", "10.0.2.102/32", "10.0.2.103/32"]
    untrust_ips: ["10.0.2.101/24", "10.0.2.102/32", "10.0.2.103/32", "10.0.2.104/32"] # list of strings
    # The ip address of the untrust gateway, if deploying to Azure, this is the first useable IP address in the subnet.
    untrust_gateway: "10.0.2.1" # string
    # The IP addresses of the trust interface of the Palo Alto firewall. Always start with a network address first followed by the additional host IPs, IE: ["10.0.1.10/24", "10.0.1.11/32"]
    trust_ips: ["10.0.1.10/24"] # list of strings
    # The IP address of the trust gateway, if deploying to azure, this is the first usable IP address in the subnet.
    trust_gateway: "10.0.1.1" # string
  vars_files:
    - provider.json # contains the credentials for the firewall

  collections:
    - paloaltonetworks.panos

  tasks:
  - name: ensure mngt profile exists to allows ping and ssh
    panos_management_profile:
      provider: '{{ provider }}'
      name: 'lb_health_check_ssh'
      ping: true
      ssh: true
  - name: Create object 'Azure_magic_ip'
    panos_address_object:
      provider: '{{provider}}'
      name: 'Azure_magic_ip'
      value: '168.63.129.16'
      description: 'Azure Magic IP for Load Balancer Checks'
  - name: Remove default admin
    panos_administrator:
      provider: '{{provider}}'
      admin_username: 'admin'
      state: absent
      commit: yes
  - name: Get trust zone info
    panos_zone_facts:
          provider: '{{ provider }}'
          name: 'trust'
    register: trustzone
    ignore_errors: True
  - name: Get untrust zone info
    panos_zone_facts:
          provider: '{{ provider }}'
          name: 'untrust'
    register: untrustzone
    ignore_errors: True
  - name: create untrust zone on a firewall
    when: untrustzone['failed'] == true
    panos_zone:
      provider: '{{ provider }}'
      zone: 'untrust'
      mode: 'layer3'
  - name: create trust zone on a firewall
    when: trustzone['failed'] == true
    panos_zone:
      provider: '{{ provider }}'
      zone: 'trust'
      mode: 'layer3'
  - name: Configure Untrust Network Interface
    panos_interface:
      provider: '{{ provider }}'
      if_name: "ethernet1/1"
      zone_name: "untrust"
      vr_name: "untrust"
      mode: "layer3"
      link_state: "auto"
      enable_dhcp: false
      ip: '{{ untrust_ips }}'
  - name: Configure Trust Network Interface
    panos_interface:
      provider: '{{ provider }}'
      if_name: "ethernet1/2"
      zone_name: "trust"
      vr_name: "default"
      mode: "layer3"
      link_state: "auto"
      create_default_route: "no"
      enable_dhcp: false
      ip: '{{ trust_ips }}'
      management_profile: 'lb_health_check_ssh'
  - name: Create Untrust Default Route
    panos_static_route:
      provider: '{{ provider }}'
      name: 'Default_Route'
      destination: '0.0.0.0/0'
      nexthop: '{{ untrust_gateway }}'
      virtual_router: 'untrust'
      interface: "ethernet1/1"
  - name: Create NextVR for return traffic
    panos_static_route:
      provider: '{{ provider }}'
      name: 'LAN_Retrun_Route'
      destination: '10.0.0.0/8'
      nexthop_type: "next-vr"
      nexthop: 'default'
      virtual_router: 'untrust'
  - name: Create Trust Default Route
    panos_static_route:
      provider: '{{ provider }}'
      name: 'Default Route'
      destination: '0.0.0.0/0'
      nexthop_type: "next-vr"
      nexthop: 'untrust'
      virtual_router: 'default'
  - name: Create Trust LB Health Check Route
    panos_static_route:
      provider: '{{ provider }}'
      name: 'Azure_LB'
      destination: '168.63.129.16/32'
      nexthop: '{{ trust_gateway }}'
      virtual_router: 'default'
      interface: "ethernet1/2"
  - name: Create Trust LAN Route 10x
    panos_static_route:
      provider: '{{ provider }}'
      name: 'LAN_RETURN_10x'
      destination: '10.0.0.0/8'
      nexthop: '{{ trust_gateway }}'
      virtual_router: 'default'
      interface: "ethernet1/2"
  - name: Create Trust LAN Route 172x
    panos_static_route:
      provider: '{{ provider }}'
      name: 'LAN_RETURN_172x'
      destination: '172.16.0.0.0/12'
      nexthop: '{{ trust_gateway }}'
      virtual_router: 'default'
      interface: "ethernet1/2"
  - name: Create Trust LAN Route 192x
    panos_static_route:
      provider: '{{ provider }}'
      name: 'LAN_RETURN_192x'
      destination: '192.168.0.0.0/16'
      nexthop: '{{ trust_gateway }}'
      virtual_router: 'default'
      interface: "ethernet1/2"
  - name: Policy -> Trust PAT Outbound
    panos_nat_rule:
      provider: '{{ provider }}'
      rule_name: "TRUST_PAT"
      source_zone: ["trust"]
      destination_zone: "untrust"
      source_ip: ["any"]
      destination_ip: ["any"]
      service: "any"
      snat_address_type: "interface-address"
      snat_type: "dynamic-ip-and-port"
      snat_interface: "ethernet1/1"
  - name: Policy -> Allow HTTP/HTTPS outbound
    panos_security_rule:
      provider: '{{ provider }}'
      rule_name: 'Trust Outbound'
      description: 'Allow Trust Outbound for Application Defaults'
      source_zone: ['trust']
      destination_zone: ['untrust']
      action: 'allow'
      commit: yes