---
- name: add ansible-pull cron job
  cron:
    name: ansible auto-provision
    user: ansible
    minute: "*/10"
    job: ansible-pull -o -U https://github.com/tpeterson66/Utopia.git --extra-vars 'ansible_user=ansible'